### ISSUE TITLE
One level too much

### ISSUE THREAD

**Issue by jief666** [SavageAUS/Clover-OC-Int#1]
Please move CLOVER, BOOT and OC.dis one level up (at the root of the repo).
Delete the now empty EFI folder.
Delete and ignore .DS_Store and ._*

**Comment by SavageAUS** [comment]
Should be resolved

**Comment by jief666** [comment]
1) Also delete all the .DS_Store. You can add this file tour your home/Library/Services and then do it from the finder.
[dot_ & DS_Store clean.workflow.zip](https://github.com/SavageAUS/Clover-OC-Int/files/5282010/dot_.DS_Store.clean.workflow.zip)

2) add ._* in .gitignore.

**Comment by jief666** [comment]
Well obviously decompress it and then add to your services folder.

**Comment by SavageAUS** [comment]
I get this when i try to run it.
![Screen Shot 2020-09-25 at 7 35 27 pm](https://user-images.githubusercontent.com/17326832/94254709-51a90580-ff66-11ea-9aaa-37c5a631bc85.png)

**Comment by jief666** [comment]
Sorry, I think it only works when you click on a folder. It'll delete in the whole tree under the folder you clicked.

**Comment by jief666** [comment]
Hum, no maybe it's not the reason. Did you right-click on the EFI folder ?

**Comment by jief666** [comment]
Ok, let restart. How did you run the script ?
The way to do it : right click the containing folder in Finder and then Services and then dot_ & DS_Store clean

**Comment by SavageAUS** [comment]
Yeah i sorted it out, never used those scripts before.
Updating master now

**Comment by jief666** [comment]
Services are so good : I have to compile an aml, to decompile, to convert a pdf, to remove tags from a mp3, etc.
I
